internetarchive/gowarc

- .github/workflows/go.yml
- client.go
- client_test.go
- dedupe.go
- dialer.go
- utils.go
- write.go
This PR adds local and remote dedupe based on a local map and the access to a remote CDX server.
Obviously, it also adds revisit records.
> Add: revisit records with local & remote CDX dedupe

- client.go
- client_test.go
- dialer.go
- transport.go
before: we had a function to verify, but it would never get called as InsecureSkipVerify was never changed, as such, things could not get archived due to invalid certificates, when we would like them to.
New: Having InsecureSkipVerify set on the tls.Config allows the normal TLS functions to check the certificate. We've configured this to a toggle on NewWARCWritingHTTPClient to allow us to turn the verification of certificates on or off.
If the setting is set to false, certificates will not be checked. If the setting is set to true, certificates are checked.
Before, it seems, we were checking every single certificate. This should give us much more consistent, expected, behavior.
> Add toggle for verifying HTTP certificates.

- client_test.go
- dialer.go
This adds a very simple Benchmark for under 2MB and over. I tested it with `rm -rf warcs && go test -bench=. -count 5`. It showed that the newer gzip (with 4 cores) [performs significantly better](https://gist.github.com/NGTmeaty/11258f9bce5ebf2ddfbeb8387636ea5a). 
And the new change added here, calculating Block-Digest on dialer.go [improves over](https://gist.github.com/NGTmeaty/8d4b0cf9c8889b3cf74b2d60b9b7c2d6) 2MB performance and doesn't change the regular.
> Add benchmark and calculate Block-Digest on dialer.go

- dialer.go
I'm genuinely unsure how we've reached this, but we shouldn't write "ERROR". If this ever happened, we shouldn't write the record, as something went wrong.
> Don't write "ERROR" for payload digest in case of error

- .github/workflows/go.yml
- client_test.go
- cmd/verify.go
- read_test.go
Variety of test improvements and minor improvements to verify.
> Various test improvements

- client.go
The idea is to prevent small payloads from being written as revisit records, as revisit records usually have a large playback cost. 2,048 bytes is seen as a better default for the time being.
> Update default size threshold to 2048 bytes

- dialer.go
Fixes an issue that was not correctly closing records when an error occurred. This is likely the case of ballooning temp folders, as when an error is returned, we can't close the record which contains the temp file.
> Correctly closing records when errors occur before sending to channel

- dialer.go
- utils.go
- utils_test.go
Refactor `isLineStartingWithHTTPMethod` to include all the logic that is necessary to validate an HTTP request (prefix and suffix).
Previously, some of the logic was in `isLineStartingWithHTTPMethod` and some was in `dialer.go` where the function was used.
Rename it to `isHTTPRequest`. (IMHO `isHTTPRequestLine` is redundant as `line` is the function param.
Add unit tests.
> Improve HTTP Request line validation

- pkg/spooledtempfile/spooled.go
- pkg/spooledtempfile/spooled_test.go
`len()` provides the size of items in the buffer
`cap()` provides the size of the allocated underlying array holding the items
`cap()` is better suited than `len()` when used to preserve memory usage
> Use cap() instead of len() to compute the spooling threshold

- pkg/spooledtempfile/spooled.go
- pkg/spooledtempfile/spooled_test.go
`spooledTempFiles` now use `[]byte` (byte slices) with pre-allocated memory and bounded growth during `Write()`  
This change should reduce the average instant usage of RAM under high-concurrency scenarios as `bytes.Buffer` tend to grow over the limit (`threshold`) before getting spooled to disk. When tens of thousands of `spooledTempFiles` are used concurrently their buffer's underlying array capacity could grow over the limit and consume more memory than predicted due to the mechanism of `bytes.growSlice` that grows the underlying array by multiplying it's capacity by 1.5 or 2 when a `buffer.Write()` would exceed current capacity.
With this PR, byte slices are used so that we have granular control over the memory usage. A `sync.Pool` manages pre-allocated byte slices of 64kB and handles …
> Refactor spooledTempFile to use byte slices instead of bytes.Buffer

- client_test.go
- dns_test.go
- header_test.go
- main_test.go
- read_test.go
- utils_test.go
Instead of using goleak in every unit test, run it in `TestMain` and it applies to all unit tests.
The project didn't have a `TestMain` so I created a `main_test.go` for that reason. `TestMain` could be added to any test file and it would work. I thought that it would be clearer to make a separate `main_test.go` file.
This method is also referenced in https://github.com/uber-go/goleak?tab=readme-ov-file#quick-start
> Improve the use of goleak in unit tests

- read.go
The current version uses `ReadString` and then converts to `[]bytes` when appending to `line`.
We can use `ReadBytes` directly and avoid that, improving performance. `bufio.reader` supports it https://pkg.go.dev/bufio#Reader.ReadBytes
Also, the `append` call is duplicate and can be called once.
> Avoid redundant bytes -> string -> bytes conversion on reading

- dialer.go
- random_local_ip.go
- random_local_ip_test.go
We converted the `net.IP` to string, pass it to `getLocalAddr` function and then convert it back to IP.
We already have it as `net.IP`, there is no need to do that.
Also, it isn't possible to have an IP with an invalid format so some unit tests are no longer needed.
> Simplify getLocalAddr by removing unnecessary IP to string conversion

- client.go
- client_test.go
- dialer.go
This allows Zeno to pass a custom discard function to determine which responses to discard without modifying warclib's code.
_This is a breaking change_.
> Replace static `SkipHTTPStatusCodes` with customizable discard hook function

- client.go
- client_test.go
- dialer.go
- discard_hook.go
ref: https://github.com/internetarchive/Zeno/pull/263#issuecomment-2793414503
Also added `DiscardHookError` error type.
---
_This is a breaking change._
> DiscardHook: return reason string

- pkg/spooledtempfile/spooled.go
We don't release the memory correctly on close.
We set `s.buf = nil` and the `if` statement after that is never executed.
Also, we double check if `s.buf != nil`, we already checked that in the previous line.
> Fix memory leak in spooledtempfile Close()

- pkg/spooledtempfile/spooled.go
There is no need to always read all /proc/meminfo lines. Stop reading as soon as we find the 2 variables that are necessary for the result.
> Optimise spooledtempfile.getSystemMemoryUsedFraction

- client.go
- dialer.go
We have `DNSServers`, `DNSServer` must be a leftover from the past.
> Remove unused DNSServer var

- client.go
The timeouts are configured via the dialer.
Go doesn't use a `TCPTimeout` var in the HTTP client. This must be a leftover variable.
> Remove unused TCPTimeout variable

- dns_test.go
Do not create multiple contexts, use the same for subsequent commands in the same test.
Do not use `panic()` on cleanup, `t.Fatalf` is better.
> Minor dns test improvements

- dialer.go
- dialer_test.go
Extract method `parseRequestTargetURI` from `readRequest` to make it more testable.
Improve the code to handle not only `Host:` but also lower/uppercase.
Add unit tests with various http request variations. Now, its easy to add more.
Also add tests for `getNetworkType`.
> Refactor readRequest and add tests

- client.go
- client_test.go
- dialer.go
1.1:
We should use the `io.PipeWriter.CloseWithError()` instead of normal `io.PipeWriter.Close()` to close connection, otherwise our warpped `io.PipeReader` (reqReader, respReader) will not get any non EOF errors on `Read()`.
1.2: `http` library mitigates this bug for us
When `http.ReadRespon()` assembles `resp.Body`, if `Content-Length` exists, its value will be used to construct `resp.Body: io.LimitReader`. 2️⃣
So, the constructed LimitReader is able to detect and return abnormal early EOF for response where the `Content-Length` header is present. 3️⃣
~~Thanks to the http standard library, it saved our lives for most responses!~~
---
This is why https://github.com/internetarchive/Zeno/pull/369 streaming response payload was not discarded and got recorded.
Solution:
When …
> FIX various bugs related to HTTP connections

- read.go
- read_test.go
That and adding a `ReadOptsNoContentOutput` to avoid passing the WARC record content block if it's not needed by the caller
> `ReadRecord()` accept opts to modulate output

- pkg/spooledtempfile/memory.go
- pkg/spooledtempfile/memory_test.go
- pkg/spooledtempfile/spooled.go
- pkg/spooledtempfile/spooled_bench_test.go
- pkg/spooledtempfile/spooled_memory.go
- pkg/spooledtempfile/spooled_test.go
This pull request refactors the memory management logic in the `spooledtempfile` package to improve buffer pooling and system memory usage detection, and adds a comprehensive benchmark suite. The most significant changes include extracting and enhancing system memory usage detection **(with container/cgroup awareness)**, improving buffer pool safety and clarity, and introducing benchmarks to measure performance across various scenarios.
**Memory usage detection improvements:**
* Moved and refactored the system memory usage detection logic into a new file, `spooled_memory.go`, with support for cgroup v2, cgroup v1, and host memory detection, making the code container-aware and more robust. (`pkg/spooledtempfile/spooled_memory.go`, `pkg/spooledtempfile/spooled.go`) …
> Add cgroups support in spooledtempfile (+ benchmarks)

- README.md
- go.mod
- gzip_interface.go
- gzip_klauspost_impl.go
- gzip_standard_impl.go
- read.go
- utils.go
- write.go
This pull request introduces an abstraction layer to support both the standard library and klauspost gzip implementations, allowing users to select the gzip backend via build tags. The changes refactor the codebase to use interface-based gzip readers and writers, making the implementation backend-agnostic. Documentation and build instructions are also updated to clarify the new options.
**Gzip backend abstraction and implementation:**
* Added `GzipWriterInterface` and `GzipReaderInterface` interfaces in `gzip_interface.go` to abstract gzip operations and enable switching implementations via build tags.
* Implemented klauspost gzip backend in `gzip_klauspost_impl.go` (default) and standard library gzip backend in `gzip_standard_impl.go` (selectable with `standard_gzip` build tag). …
> Add standard_gzip build tag to use standard Go gzip package
